import React, { useState } from 'react';
import { Save, Download, FileText, Calendar, DollarSign, Clock } from 'lucide-react';
import ShellkodeLogo from './ShellkodeLogo';
import './SOWForm.css';
import './ShellkodeLogo.css';

interface SOWFormProps {
  sowType: string;
  sowTitle: string;
}

interface FormData {
  clientName: string;
  projectName: string;
  startDate: string;
  endDate: string;
  budget: string;
  description: string;
  scope: string;
  deliverables: string;
  timeline: string;
  assumptions: string;
}

const SOWForm: React.FC<SOWFormProps> = ({ sowType, sowTitle }) => {
  const [formData, setFormData] = useState<FormData>({
    clientName: '',
    projectName: '',
    startDate: '',
    endDate: '',
    budget: '',
    description: '',
    scope: '',
    deliverables: '',
    timeline: '',
    assumptions: ''
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSave = () => {
    console.log('Saving SOW:', formData);
    // Here you would typically save to a backend
    alert('SOW saved successfully!');
  };

  const handleExport = () => {
    const sowContent = generateSOWContent();
    const blob = new Blob([sowContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${formData.projectName || 'SOW'}_${sowType}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateSOWContent = () => {
    return `
STATEMENT OF WORK
${sowTitle}

CLIENT INFORMATION:
Client Name: ${formData.clientName}
Project Name: ${formData.projectName}

PROJECT TIMELINE:
Start Date: ${formData.startDate}
End Date: ${formData.endDate}

BUDGET:
${formData.budget}

PROJECT DESCRIPTION:
${formData.description}

SCOPE OF WORK:
${formData.scope}

DELIVERABLES:
${formData.deliverables}

TIMELINE:
${formData.timeline}

ASSUMPTIONS:
${formData.assumptions}

Generated by Shellkode SOW Creator
Date: ${new Date().toLocaleDateString()}
    `.trim();
  };

  return (
    <div className="sow-form-container">
      <div className="form-header">
        <div className="form-title-section">
          <ShellkodeLogo size="small" logoOnly />
          <div>
            <h2>{sowTitle}</h2>
            <p>Create a comprehensive statement of work</p>
          </div>
        </div>
        
        <div className="form-actions">
          <button className="action-btn save-btn" onClick={handleSave}>
            <Save className="btn-icon" />
            Save Draft
          </button>
          <button className="action-btn export-btn" onClick={handleExport}>
            <Download className="btn-icon" />
            Export SOW
          </button>
        </div>
      </div>

      <form className="sow-form">
        <div className="form-section">
          <h3>Client Information</h3>
          <div className="form-grid">
            <div className="form-group">
              <label htmlFor="clientName">Client Name</label>
              <input
                type="text"
                id="clientName"
                name="clientName"
                value={formData.clientName}
                onChange={handleInputChange}
                placeholder="Enter client name"
                className="form-input"
              />
            </div>
            <div className="form-group">
              <label htmlFor="projectName">Project Name</label>
              <input
                type="text"
                id="projectName"
                name="projectName"
                value={formData.projectName}
                onChange={handleInputChange}
                placeholder="Enter project name"
                className="form-input"
              />
            </div>
          </div>
        </div>

        <div className="form-section">
          <h3>Project Timeline & Budget</h3>
          <div className="form-grid">
            <div className="form-group">
              <label htmlFor="startDate">
                <Calendar className="label-icon" />
                Start Date
              </label>
              <input
                type="date"
                id="startDate"
                name="startDate"
                value={formData.startDate}
                onChange={handleInputChange}
                className="form-input"
              />
            </div>
            <div className="form-group">
              <label htmlFor="endDate">
                <Calendar className="label-icon" />
                End Date
              </label>
              <input
                type="date"
                id="endDate"
                name="endDate"
                value={formData.endDate}
                onChange={handleInputChange}
                className="form-input"
              />
            </div>
            <div className="form-group">
              <label htmlFor="budget">
                <DollarSign className="label-icon" />
                Budget
              </label>
              <input
                type="text"
                id="budget"
                name="budget"
                value={formData.budget}
                onChange={handleInputChange}
                placeholder="e.g., $50,000 - $75,000"
                className="form-input"
              />
            </div>
          </div>
        </div>

        <div className="form-section">
          <h3>Project Description</h3>
          <div className="form-group">
            <label htmlFor="description">Description</label>
            <textarea
              id="description"
              name="description"
              value={formData.description}
              onChange={handleInputChange}
              placeholder="Provide a detailed description of the project..."
              className="form-textarea"
              rows={4}
            />
          </div>
        </div>

        <div className="form-section">
          <h3>Scope of Work</h3>
          <div className="form-group">
            <label htmlFor="scope">Scope Details</label>
            <textarea
              id="scope"
              name="scope"
              value={formData.scope}
              onChange={handleInputChange}
              placeholder="Define the scope of work, including what is and isn't included..."
              className="form-textarea"
              rows={6}
            />
          </div>
        </div>

        <div className="form-section">
          <h3>Deliverables</h3>
          <div className="form-group">
            <label htmlFor="deliverables">Expected Deliverables</label>
            <textarea
              id="deliverables"
              name="deliverables"
              value={formData.deliverables}
              onChange={handleInputChange}
              placeholder="List all deliverables and their specifications..."
              className="form-textarea"
              rows={5}
            />
          </div>
        </div>

        <div className="form-section">
          <h3>Timeline & Assumptions</h3>
          <div className="form-grid">
            <div className="form-group">
              <label htmlFor="timeline">
                <Clock className="label-icon" />
                Detailed Timeline
              </label>
              <textarea
                id="timeline"
                name="timeline"
                value={formData.timeline}
                onChange={handleInputChange}
                placeholder="Break down the project timeline with milestones..."
                className="form-textarea"
                rows={4}
              />
            </div>
            <div className="form-group">
              <label htmlFor="assumptions">Assumptions</label>
              <textarea
                id="assumptions"
                name="assumptions"
                value={formData.assumptions}
                onChange={handleInputChange}
                placeholder="List any assumptions made for this project..."
                className="form-textarea"
                rows={4}
              />
            </div>
          </div>
        </div>
      </form>
    </div>
  );
};

export default SOWForm;