import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import { Download, FilePlus, Search } from 'lucide-react';
import apiService, { Document } from '../services/apiService';
import { downloadWithNativeSaveAs } from '../utils/downloadFile';
import './Dashboard.css';
import './SOWRecords.css';

type HistoryRecord = Document & {
  document?: Document;
  task?: { metadata?: Document };
};

const documentData = (record: HistoryRecord): Document => record.document || record;
const taskMetadata = (record: HistoryRecord): Document => record.task?.metadata || {};

const recordDate = (record: Document): string => (
  record.timestamp || record.created_at || record.document_date || record.date || ''
);

const displayDate = (record: Document): string => {
  const value = recordDate(record);
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? value
    : date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
};

const generatedAt = (record: HistoryRecord): number => {
  const parsed = new Date(recordDate(documentData(record))).getTime();
  return Number.isFinite(parsed) ? parsed : 0;
};

const sowName = (record: HistoryRecord): string => {
  const document = documentData(record);
  const metadata = taskMetadata(record);
  const project = document.project_name || document.name || document.title || metadata.project_name || 'Untitled SOW';
  const suffix = [document.mode || record.task?.metadata?.mode, document.version].filter(Boolean).join(' ');
  return suffix ? `${project} - ${suffix}` : project;
};

const SOWRecords: React.FC = () => {
  const navigate = useNavigate();
  const [records, setRecords] = useState<HistoryRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    let active = true;
    apiService.fetchDocuments({ mine: true, limit: 1000 }).then(response => {
      if (!active) return;
      if (!response.success) toast.error('Unable to load your SOW records');
      setRecords([...(response.documents || [])].sort((a, b) => generatedAt(b) - generatedAt(a)));
      setLoading(false);
    });
    return () => { active = false; };
  }, []);

  const filteredRecords = useMemo(() => {
    const query = searchQuery.trim().toLowerCase();
    if (!query) return records;
    return records.filter(record => {
      const document = documentData(record);
      const metadata = taskMetadata(record);
      return (
      `${sowName(record)} ${document.business_unit || metadata.business_unit || ''} ${document.owner_name || metadata.owner_name || document.author_name || document.author || ''}`
        .toLowerCase()
        .includes(query)
      );
    });
  }, [records, searchQuery]);

  const download = async (record: HistoryRecord) => {
    const document = documentData(record);
    const url = document.s3_url || document.drive_link || '';
    if (!url) {
      toast.error('This SOW does not have a downloadable document');
      return;
    }
    const filename = `${sowName(record).replace(/[<>:"/\\|?*]/g, '_')}.docx`;
    try {
      await downloadWithNativeSaveAs(
        () => apiService.downloadDocument(url, document.document_id),
        filename,
      );
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Download failed');
    }
  };

  return (
    <div className="records-view sow-records-page">
      <div className="records-header">
        <div className="records-header-left">
          <h1>SOW Records</h1>
          <p>All SOW documents generated by your account</p>
        </div>
        <div className="records-search-container">
          <Search className="records-search-icon" size={14} />
          <input
            type="text"
            placeholder="Search your SOW records..."
            className="records-search-input"
            value={searchQuery}
            onChange={(event) => setSearchQuery(event.target.value)}
          />
        </div>
      </div>

      <div className="records-table-container">
        <table className="records-table">
          <thead><tr>
            <th>SOW Name</th>
            <th>Business Unit</th>
            <th>Created By</th>
            <th>Created Date</th>
            <th style={{ textAlign: 'center' }}>Actions</th>
          </tr></thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={5} className="no-records">Loading your SOW records…</td></tr>
            ) : filteredRecords.length === 0 ? (
              <tr><td colSpan={5} className="no-records">
                <div className="sow-empty-state">
                  <FilePlus size={32} />
                  <p className="sow-empty-title">No SOWs found</p>
                  <p className="sow-empty-subtitle">
                    {records.length ? 'No records match your search.' : "You haven't generated any SOWs yet."}
                  </p>
                  {!records.length && <button type="button" className="sow-empty-cta" onClick={() => navigate('/dashboard')}>Create SOW</button>}
                </div>
              </td></tr>
            ) : filteredRecords.map(record => {
              const document = documentData(record);
              const metadata = taskMetadata(record);
              return (
              <tr key={`${document.document_id || document.id}-${document.timestamp || document.version}`}>
                <td><div className="sow-name-cell">{sowName(record)}</div></td>
                <td>{document.business_unit || metadata.business_unit || 'Unassigned'}</td>
                <td>{document.owner_name || metadata.owner_name || document.author_name || document.author || metadata.author_name || 'Unknown'}</td>
                <td>{displayDate(document)}</td>
                <td><div className="action-buttons">
                  <button className="download-icon-btn" title="Download SOW" onClick={() => download(record)}>
                    <Download size={16} />
                  </button>
                </div></td>
              </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default SOWRecords;
